// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/exchange/exchange.proto

package exchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_USD                  Currency = 1
	Currency_EUR                  Currency = 2
	Currency_RUB                  Currency = 3
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "USD",
		2: "EUR",
		3: "RUB",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"USD":                  1,
		"EUR":                  2,
		"RUB":                  3,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_exchange_exchange_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_proto_exchange_exchange_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_proto_exchange_exchange_proto_rawDescGZIP(), []int{0}
}

type ExchangeRatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Базовая валюта, относительно которой будут отданы rates
	BaseCurrency  Currency `protobuf:"varint,1,opt,name=base_currency,json=baseCurrency,proto3,enum=exchange.Currency" json:"base_currency,omitempty"` // по умолчанию USD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRatesRequest) Reset() {
	*x = ExchangeRatesRequest{}
	mi := &file_proto_exchange_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRatesRequest) ProtoMessage() {}

func (x *ExchangeRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRatesRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_exchange_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRatesRequest) GetBaseCurrency() Currency {
	if x != nil {
		return x.BaseCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type CurrencyPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  Currency               `protobuf:"varint,1,opt,name=from_currency,json=fromCurrency,proto3,enum=exchange.Currency" json:"from_currency,omitempty"`
	ToCurrency    Currency               `protobuf:"varint,2,opt,name=to_currency,json=toCurrency,proto3,enum=exchange.Currency" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyPairRequest) Reset() {
	*x = CurrencyPairRequest{}
	mi := &file_proto_exchange_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyPairRequest) ProtoMessage() {}

func (x *CurrencyPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyPairRequest.ProtoReflect.Descriptor instead.
func (*CurrencyPairRequest) Descriptor() ([]byte, []int) {
	return file_proto_exchange_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyPairRequest) GetFromCurrency() Currency {
	if x != nil {
		return x.FromCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *CurrencyPairRequest) GetToCurrency() Currency {
	if x != nil {
		return x.ToCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type ExchangeRateResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency Currency               `protobuf:"varint,1,opt,name=from_currency,json=fromCurrency,proto3,enum=exchange.Currency" json:"from_currency,omitempty"`
	ToCurrency   Currency               `protobuf:"varint,2,opt,name=to_currency,json=toCurrency,proto3,enum=exchange.Currency" json:"to_currency,omitempty"`
	// Лучше double, но ещё лучше — использовать fixed-point (см. ниже)
	Rate float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"` // 1 from_currency = rate to_currency
	// Когда курс был актуализирован
	UpdatedAtUnix int64 `protobuf:"varint,4,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateResponse) Reset() {
	*x = ExchangeRateResponse{}
	mi := &file_proto_exchange_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateResponse) ProtoMessage() {}

func (x *ExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_exchange_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRateResponse) GetFromCurrency() Currency {
	if x != nil {
		return x.FromCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *ExchangeRateResponse) GetToCurrency() Currency {
	if x != nil {
		return x.ToCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *ExchangeRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRateResponse) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type ExchangeRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseCurrency  Currency               `protobuf:"varint,1,opt,name=base_currency,json=baseCurrency,proto3,enum=exchange.Currency" json:"base_currency,omitempty"`
	Rates         map[string]float64     `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRatesResponse) Reset() {
	*x = ExchangeRatesResponse{}
	mi := &file_proto_exchange_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRatesResponse) ProtoMessage() {}

func (x *ExchangeRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRatesResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_exchange_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeRatesResponse) GetBaseCurrency() Currency {
	if x != nil {
		return x.BaseCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *ExchangeRatesResponse) GetRates() map[string]float64 {
	if x != nil {
		return x.Rates
	}
	return nil
}

var File_proto_exchange_exchange_proto protoreflect.FileDescriptor

const file_proto_exchange_exchange_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/exchange/exchange.proto\x12\bexchange\"O\n" +
	"\x14ExchangeRatesRequest\x127\n" +
	"\rbase_currency\x18\x01 \x01(\x0e2\x12.exchange.CurrencyR\fbaseCurrency\"\x83\x01\n" +
	"\x13CurrencyPairRequest\x127\n" +
	"\rfrom_currency\x18\x01 \x01(\x0e2\x12.exchange.CurrencyR\ffromCurrency\x123\n" +
	"\vto_currency\x18\x02 \x01(\x0e2\x12.exchange.CurrencyR\n" +
	"toCurrency\"\xc0\x01\n" +
	"\x14ExchangeRateResponse\x127\n" +
	"\rfrom_currency\x18\x01 \x01(\x0e2\x12.exchange.CurrencyR\ffromCurrency\x123\n" +
	"\vto_currency\x18\x02 \x01(\x0e2\x12.exchange.CurrencyR\n" +
	"toCurrency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12&\n" +
	"\x0fupdated_at_unix\x18\x04 \x01(\x03R\rupdatedAtUnix\"\xcc\x01\n" +
	"\x15ExchangeRatesResponse\x127\n" +
	"\rbase_currency\x18\x01 \x01(\x0e2\x12.exchange.CurrencyR\fbaseCurrency\x12@\n" +
	"\x05rates\x18\x02 \x03(\v2*.exchange.ExchangeRatesResponse.RatesEntryR\x05rates\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01*?\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03USD\x10\x01\x12\a\n" +
	"\x03EUR\x10\x02\x12\a\n" +
	"\x03RUB\x10\x032\xc3\x01\n" +
	"\x0fExchangeService\x12S\n" +
	"\x10GetExchangeRates\x12\x1e.exchange.ExchangeRatesRequest\x1a\x1f.exchange.ExchangeRatesResponse\x12[\n" +
	"\x1aGetExchangeRateForCurrency\x12\x1d.exchange.CurrencyPairRequest\x1a\x1e.exchange.ExchangeRateResponseBEZCgithub.com/motru4/legendary-currency-wallet/proto/exchange;exchangeb\x06proto3"

var (
	file_proto_exchange_exchange_proto_rawDescOnce sync.Once
	file_proto_exchange_exchange_proto_rawDescData []byte
)

func file_proto_exchange_exchange_proto_rawDescGZIP() []byte {
	file_proto_exchange_exchange_proto_rawDescOnce.Do(func() {
		file_proto_exchange_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exchange_exchange_proto_rawDesc), len(file_proto_exchange_exchange_proto_rawDesc)))
	})
	return file_proto_exchange_exchange_proto_rawDescData
}

var file_proto_exchange_exchange_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_exchange_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_exchange_exchange_proto_goTypes = []any{
	(Currency)(0),                 // 0: exchange.Currency
	(*ExchangeRatesRequest)(nil),  // 1: exchange.ExchangeRatesRequest
	(*CurrencyPairRequest)(nil),   // 2: exchange.CurrencyPairRequest
	(*ExchangeRateResponse)(nil),  // 3: exchange.ExchangeRateResponse
	(*ExchangeRatesResponse)(nil), // 4: exchange.ExchangeRatesResponse
	nil,                           // 5: exchange.ExchangeRatesResponse.RatesEntry
}
var file_proto_exchange_exchange_proto_depIdxs = []int32{
	0, // 0: exchange.ExchangeRatesRequest.base_currency:type_name -> exchange.Currency
	0, // 1: exchange.CurrencyPairRequest.from_currency:type_name -> exchange.Currency
	0, // 2: exchange.CurrencyPairRequest.to_currency:type_name -> exchange.Currency
	0, // 3: exchange.ExchangeRateResponse.from_currency:type_name -> exchange.Currency
	0, // 4: exchange.ExchangeRateResponse.to_currency:type_name -> exchange.Currency
	0, // 5: exchange.ExchangeRatesResponse.base_currency:type_name -> exchange.Currency
	5, // 6: exchange.ExchangeRatesResponse.rates:type_name -> exchange.ExchangeRatesResponse.RatesEntry
	1, // 7: exchange.ExchangeService.GetExchangeRates:input_type -> exchange.ExchangeRatesRequest
	2, // 8: exchange.ExchangeService.GetExchangeRateForCurrency:input_type -> exchange.CurrencyPairRequest
	4, // 9: exchange.ExchangeService.GetExchangeRates:output_type -> exchange.ExchangeRatesResponse
	3, // 10: exchange.ExchangeService.GetExchangeRateForCurrency:output_type -> exchange.ExchangeRateResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_exchange_exchange_proto_init() }
func file_proto_exchange_exchange_proto_init() {
	if File_proto_exchange_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exchange_exchange_proto_rawDesc), len(file_proto_exchange_exchange_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exchange_exchange_proto_goTypes,
		DependencyIndexes: file_proto_exchange_exchange_proto_depIdxs,
		EnumInfos:         file_proto_exchange_exchange_proto_enumTypes,
		MessageInfos:      file_proto_exchange_exchange_proto_msgTypes,
	}.Build()
	File_proto_exchange_exchange_proto = out.File
	file_proto_exchange_exchange_proto_goTypes = nil
	file_proto_exchange_exchange_proto_depIdxs = nil
}
